# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwsClockingCli < Formula
  desc "Clocking in/out cli for COMPANY Web Service."
  homepage "https://github.com/yano3/cws-clocking-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yano3/cws-clocking-cli/releases/download/v0.2.0/cws-clocking-cli_darwin_amd64.zip"
      sha256 "da4c6e3dcb45312f91f28769e6381cb2d077646dbf51ca679df31f181b4809f4"

      def install
        bin.install "cws-clocking-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yano3/cws-clocking-cli/releases/download/v0.2.0/cws-clocking-cli_darwin_arm64.zip"
      sha256 "309ad2d12654a24d5243907e901ccc57a0290eab533f183525538312f1e924e9"

      def install
        bin.install "cws-clocking-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yano3/cws-clocking-cli/releases/download/v0.2.0/cws-clocking-cli_linux_amd64.zip"
      sha256 "1b0687ac67da079fb8010fcd00bda18c6db50bc9d0af196c9ce8aa0e00e77e34"

      def install
        bin.install "cws-clocking-cli"
      end
    end
  end
end
