# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwsClockingCli < Formula
  desc "Clocking in/out cli for COMPANY Web Service."
  homepage "https://github.com/yano3/cws-clocking-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yano3/cws-clocking-cli/releases/download/v0.2.1/cws-clocking-cli_darwin_arm64.zip"
      sha256 "1806a1a6f348e27fbeff9592b9a4ecc1be7fd062d78c8d3e3f0520b24d499f78"

      def install
        bin.install "cws-clocking-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yano3/cws-clocking-cli/releases/download/v0.2.1/cws-clocking-cli_darwin_amd64.zip"
      sha256 "e9b4983f5de5cfd131ba1f64c101973d00fde6e090c424802b462e9ae7917ff6"

      def install
        bin.install "cws-clocking-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yano3/cws-clocking-cli/releases/download/v0.2.1/cws-clocking-cli_linux_amd64.zip"
      sha256 "e6bf490e159b2dc5b6fba0225d1c493fd3352adcb3cdd1469d5d9884cfb2adfd"

      def install
        bin.install "cws-clocking-cli"
      end
    end
  end
end
